version: "3"
services:
  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: "postgres:12"
    hostname: database_host
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_users
      - POSTGRES_PASSWORD=123456
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
